config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :phones, controller: 'phones'
  resources :tablets, controller: 'tablets'
  resources :transformers, controller: 'transformers'
  resources :watches, controller: 'watches'

  root 'main#index'

  resources :phones do
    resources :developers, controller: 'developers'
  end

  root 'phones#index'

  resources :tablets do
    resources :developers, controller: 'developers'
  end

  root 'tablets#index'

  resources :watches do
    resources :developers, controller: 'developers'
  end

  root 'watches#index'

  resources :transformers do
    resources :developers, controller: 'developers'
  end

  root 'transformers#index'

  resources :developers do
    resources :phones, controller: 'phones'
    resources :tablets, controller: 'tablets'
    resources :transformers, controller: 'transformers'
    resources :watches, controller: 'watches'
  end

  root 'developers#index'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @phones = Phone.all
    @tablets = Tablet.all
    @transformers = Transformer.all
    @watches = Watch.all
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_form.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:l, "Search for:") %>
  <%= text_field_tag(:t) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/main/index.html.erb
<main>
  <header>
    <h1>Вы ищете...</h1>
    <div>
      <%= link_to phones_path, controller: 'phones' do %>
        <figure>
          <%= image_tag 'icons/smartphone.svg' %>
          <h3>телефон</h3>
        </figure>
      <% end %>
      <%= link_to tablets_path, controller: 'tablets' do %>
        <figure>
            <%= image_tag 'icons/tablet.svg' %>
            <h3>планшет</h3>
          </figure>
      <% end %>
      <%= link_to transformers_path, controller: 'transformers' do %>
        <figure>
            <%= image_tag 'icons/laptop.svg' %>
            <h3>ноутбук</h3>
          </figure>
      <% end %>
      <%= link_to watches_path, controller: 'watches' do %>
        <figure>
            <%= image_tag 'icons/watch.svg' %>
            <h3>часы</h3>
          </figure>
      <% end %>
    </div>
    <p class="bottom-heading">Больше интересных гаджетов ниже</p>
  </header>
  <div class="container">
    <h2>Телефоны</h2>
    <section class="line">
      <div>
        <% @phones.each do |phone| %>
          <%= link_to phones_path(phone) do %>
            <article>
              <%= image_tag 'phones/'+phone.model, alt: phone.model %>
              <p><%= phone.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    <h2>Планшеты</h2>
    <section class="line">
      <div>
        <% @tablets.each do |tablet| %>
          <%= link_to tablets_path(tablet) do %>
            <article>
              <%= image_tag 'tablets/'+tablet.model, alt: tablet.model %>
              <p><%= tablet.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    <h2>Трансформеры</h2>
    <section class="line">
      <div>
        <% @transformers.each do |transformer| %>
          <%= link_to transformers_path(transformer) do %>
            <article>
              <%= image_tag 'transformers/'+transformer.model, alt: transformer.model %>
              <p><%= transformer.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    <h2>Умные часы</h2>
    <section class="line">
      <div>
        <% @watches.each do |watch| %>
          <%= link_to watches_path(watch) do %>
            <article>
              <%= image_tag 'watches/'+watch.model, alt: watch.model %>
              <p><%= watch.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</main>