config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :phones, controller: 'phones'
  resources :tablets, controller: 'tablets'
  resources :transformers, controller: 'transformers'
  resources :watches, controller: 'watches'

  root 'main#index'

  resources :phones do
    resources :developers, controller: 'developers'
  end

  root 'phones#index'

  resources :tablets do
    resources :developers, controller: 'developers'
  end

  root 'tablets#index'

  resources :watches do
    resources :developers, controller: 'developers'
  end

  root 'watches#index'

  resources :transformers do
    resources :developers, controller: 'developers'
  end

  root 'transformers#index'

  resources :developers do
    resources :phones, controller: 'phones'
    resources :tablets, controller: 'tablets'
    resources :transformers, controller: 'transformers'
    resources :watches, controller: 'watches'
  end

  root 'developers#index'
end

app/models/developer.rb
class Developer < ApplicationRecord
  has_many :phones
  has_many :tablets
  has_many :transformers
  has_many :watches
  validates :name, presence: true,
                   length: { minimum: 3 }
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

  http_basic_authenticate_with name: 'Twirx', password: 'maslenak', except: [:index, :show]

  def index
    @developers = Developer.all
  end

  def show
    @developer = Developer.find(params[:id])
    @phones = Phone.all
    @tablets = Tablet.all
    @transformers = Transformer.all
    @watches = Watch.all
  end

  def new
    @developer = Developer.new
    @phones = Phone.all
    @tablets = Tablet.all
    @transformers = Transformer.all
    @watches = Watch.all
  end

  def edit
    @developer = Developer.find(params[:id])
    @phones = Phone.all
    @tablets = Tablet.all
    @transformers = Transformer.all
    @watches = Watch.all
  end

  def create
    @developer = Developer.new(developer_params)

    if @developer.save
      redirect_to @developer
    else
      render 'new'
    end
  end

  def update
    @developer = Developer.find(params[:id])

    if @developer.update(developer_params)
      redirect_to @developer
    else
      render 'edit'
    end
  end

  def destroy
    @developer = Developer.find(params[:id])
    @developer.destroy

    redirect_to developers_path
  end

  private
    def developer_params
      params.require(:developer).permit(:name, :description, :devices, :founded, :founders)
    end
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_form.html.erb
<main>
  <div class="container">
    <h2>Разработчик</h2>
    <%= form_for @developer do |f| %>
    <% if @developer.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@developer.errors.count, "error") %> prohibited
          this developer from being saved:
        </h2>
        <ul>
          <% @developer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <section class="device-form">
        <figure>
          <%= f.label :name, "Название" %>
          <%= f.text_field :name %>
        </figure>
        <figure>
          <%= f.label :founded, "Основана" %>
          <%= f.text_field :founded %>
        </figure>
        <figure>
          <%= f.label :founders, "Основатели" %>
          <%= f.text_field :founders %>
        </figure>
        <figure>
          <%= f.label :description, "Описание" %>
          <%= f.text_area :description %>
        </figure>
        <figure>
          <p>Устройства:</p>
          <select>
            <% @phones.each do |phone| %>
              <option><%= phone.model %></option>
            <% end %>
            <% @tablets.each do |tablet| %>
              <option><%= tablet.model %></option>
            <% end %>
            <% @watches.each do |watch| %>
              <option><%= watch.model %></option>
            <% end %>
            <% @transformers.each do |transformer| %>
              <option><%= transformer.model %></option>
            <% end %>
          </select>
        </figure>
        <%= f.submit(class: "button", value: "Обновить") %>
        <%= link_to "Назад", developers_path, class: "button" %>
      </section>
    <% end %>
  </div>
</main>

app/views/developers/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/index.html.erb
<main>
  <div class="container">
    <h2>Разработчики</h2>
    <section class="line">
      <div>
        <% @developers.each do |developer| %>
          <%= link_to developer_path(developer) do %>
            <article>
              <%= image_tag 'developers/'+developer.name, alt: developer.name %>
              <p><%= developer.name %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</main>

app/views/developers/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', developers_path %>

app/views/developers/show.html.erb
<main>
  <div class="container">
    <%= link_to developers_path do %><h2>Разработчики<% end %> > <%= @developer.name %></h2>
    <section class="gadget-head">
      <div class="img-box">
          <%= image_tag 'developers/'+@developer.name %>
      </div>
      <div class="main-specs">
        <h1 class="gadget-caption"><%= @developer.name %></h1>
        <table class="specs">
          <caption>Основная информация:</caption>
          <tr>
            <td>Год основания:</td>
            <td><%= @developer.founded %></td>
          </tr>
          <tr>
            <td>Основатели:</td>
            <td><%= @developer.founders %></td>
          </tr>
        </table>
      </div>
      <div class="edit-buttons">
        <%= link_to 'Редактировать', edit_developer_path(@developer), class: "button" %>
        <%= link_to 'Удалить', developer_path(@developer), method: :delete, data: { confirm: 'Вы уверены?' }, class: "button attention" %>
      </div>
    </section>
    <table class="specs">
      <caption>Дополнительная информация:</caption>
      <tr>
        <td class="sub-heading">Описание:</td>
      </tr>
      <tr>
        <td colspan="4"><%= @developer.description %></td>
      </tr>
    </table>
    <h2>Телефоны:</h2>
    <section class="line">
      <div>
        <% @phones.each do |phone| %>
          <%= link_to phone_path(phone) do %>
            <article>
              <%= image_tag 'phones/'+phone.model, alt: phone.model %>
              <p><%= @developer.name %> <%= phone.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    <h2>Планшеты:</h2>
    <section class="line">
      <div>
        <% @tablets.each do |tablet| %>
          <%= link_to tablet_path(tablet) do %>
            <article>
              <%= image_tag 'tablets/'+tablet.model, alt: tablet.model %>
              <p><%= @developer.name %> <%= tablet.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    <h2>Трансформеры:</h2>
    <section class="line">
      <div>
        <% @transformers.each do |transformer| %>
          <%= link_to transformer_path(transformer) do %>
            <article>
              <%= image_tag 'transformers/'+transformer.model, alt: transformer.model %>
              <p><%= @developer.name %> <%= transformer.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    <h2>Телефоны:</h2>
    <section class="line">
      <div>
        <% @watches.each do |watch| %>
          <%= link_to watch_path(watch) do %>
            <article>
              <%= image_tag 'watches/'+watch.model, alt: watch.model %>
              <p><%= @developer.name %> <%= watch.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
    </div>
  <%= render 'layouts/footer' %>
</main>