config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :phones, controller: 'phones'
  resources :tablets, controller: 'tablets'
  resources :transformers, controller: 'transformers'
  resources :watches, controller: 'watches'

  root 'main#index'

  resources :phones do
    resources :developers, controller: 'developers'
  end

  root 'phones#index'

  resources :tablets do
    resources :developers, controller: 'developers'
  end

  root 'tablets#index'

  resources :watches do
    resources :developers, controller: 'developers'
  end

  root 'watches#index'

  resources :transformers do
    resources :developers, controller: 'developers'
  end

  root 'transformers#index'

  resources :developers do
    resources :phones, controller: 'phones'
    resources :tablets, controller: 'tablets'
    resources :transformers, controller: 'transformers'
    resources :watches, controller: 'watches'
  end

  root 'developers#index'
end

app/models/tablet.rb
class Tablet < ApplicationRecord
  has_one :developer
  validates :model, presence: true,
                        length: { minimum: 3 }
end

app/controllers/tablets_controller.rb
class TabletsController < ApplicationController

  http_basic_authenticate_with name: 'Twirx', password: 'maslenak', except: [:index, :show]

  def index
    @tablets = Tablet.all
  end

  def show
    @tablet = Tablet.find(params[:id])
    @developer = Developer.find(params[:id])
  end

  def new
    @tablet = Tablet.new
    @developers = Developer.all
  end

  def edit
    @tablet = Tablet.find(params[:id])
    @developers = Developer.all
  end

  def create
    @tablet = Tablet.new(tablet_params)
    @developers = Developer.all

    if @tablet.save
      redirect_to @tablet
    else
      render 'new'
    end
  end

  def update
    @tablet = Tablet.find(params[:id])
    @developers = Developer.all

    if @tablet.update(tablet_params)
      redirect_to @tablet
    else
      render 'edit'
    end
  end

  def destroy
    @tablet = Tablet.find(params[:id])
    @tablet.destroy

    redirect_to tablets_path
  end

  private
    def tablet_params
      params.require(:tablet).permit(:model, :description, :m_year, :resolution_x, :resolution_y, :diagonal, :screen_type, :dpi, :multitouch, :cpu, :cores, :frequency, :gpu, :inner_mem, :ram, :cam, :megapixels, :photo_res_x, :photo_res_y, :hdr, :front_megapixels, :video_res_x, :video_res_y, :fps, :phone, :three_g, :four_g, :wifi, :bluetooth, :nfc, :gyroscope, :accelerometer, :light_sensor, :proximity, :sim, :glonass, :disp_protect, :card, :card_max, :compass, :autofocus, :diaphragm, :jack, :wireless_charge, :fast_charge, :type_c, :battery, :standby_time, :talk_time, :os, :color, :weight, :dimensions, :material, :protection)
    end
end

app/helpers/tablets_helper.rb
module TabletsHelper
end

app/views/tablets/_form.html.erb
<main>
  <div class="container">
    <h2>Планшет <%= @tablet.model %></h2>
    <%= form_for @tablet do |f| %>
      <% if @tablet.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@tablet.errors.count, "error") %> prohibited
            this phone from being saved:
          </h2>
          <ul>
            <% @tablet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <section class="device-form">
        <figure>
          <p>Разработчик</p>
          <select>
            <% @developers.each do |developer| %>
              <option><%= developer.name %></option>
            <% end %>
          </select>
        </figure>
        <figure>
          <%= f.label :model, "Модель" %>
          <%= f.text_field :model %>
        </figure>
        <figure>
          <%= f.label :m_year, "Год выхода" %>
          <%= f.text_field :m_year %>
        </figure>
        <figure>
          <%= f.label :resolution_x, "Разрешение экрана (x)" %>
          <%= f.text_field :resolution_x %>
        </figure>
        <figure>
          <%= f.label :resolution_y, "Разрешение экрана (y)" %>
          <%= f.text_field :resolution_y %>
        </figure>
        <figure>
          <%= f.label :diagonal, "Диагональ экрана" %>
          <%= f.text_field :diagonal %>
        </figure>
        <figure>
          <%= f.label :screen_type, "Тип экрана" %>
          <%= f.text_field :screen_type %>
        </figure>
        <figure>
          <%= f.label :dpi, "DPI" %>
          <%= f.text_field :dpi %>
        </figure>
        <figure>
          <%= f.label :multitouch, "Кол-во одновременных касаний" %>
          <%= f.text_field :multitouch %>
        </figure>
        <figure>
          <%= f.label :disp_protect, "Защита дисплея" %>
          <%= f.text_field :disp_protect %>
        </figure>
        <figure>
          <%= f.label :cpu, "Процессор" %>
          <%= f.text_field :cpu %>
        </figure>
        <figure>
          <%= f.label :cores, "Кол-во ядер" %>
          <%= f.text_field :cores %>
        </figure>
        <figure>
          <%= f.label :frequency, "Частота процессора" %>
          <%= f.text_field :frequency %>
        </figure>
        <figure>
          <%= f.label :gpu, "Графический процессор"%>
          <%= f.text_field :gpu %>
        </figure>
        <figure>
          <%= f.label :inner_mem, "Объем внутр. памяти" %>
          <%= f.text_field :inner_mem %>
        </figure>
        <figure>
          <%= f.label :ram, "Объем опер. памяти" %>
          <%= f.text_field :ram %>
        </figure>
        <figure>
          <%= f.label :cam, "Модуль камеры" %>
          <%= f.text_field :cam %>
        </figure>
        <figure>
          <%= f.label :megapixels, "Кол-во Mp основной камеры" %>
          <%= f.text_field :megapixels %>
        </figure>
        <figure>
          <%= f.label :diaphragm, "Диафрагма" %>
          <%= f.text_field :diaphragm %>
        </figure>
        <figure>
          <%= f.label :autofocus, "Автофокус" %>
          <%= f.text_field :autofocus %>
        </figure>
        <figure>
          <%= f.label :photo_res_x, "Разрешение фото (x)" %>
          <%= f.text_field :photo_res_x %>
        </figure>
        <figure>
          <%= f.label :photo_res_y, "Разрешение фото (y)" %>
          <%= f.text_field :photo_res_y %>
        </figure>
        <figure>
          <%= f.label :front_megapixels, "Кол-во Mp фронтальной камеры" %>
          <%= f.text_field :front_megapixels %>
        </figure>
        <figure>
          <%= f.label :video_res_x, "Разрешение видео (x)" %>
          <%= f.text_field :video_res_x %>
        </figure>
        <figure>
          <%= f.label :video_res_y, "Разрешение видео (y)" %>
          <%= f.text_field :video_res_y %>
        </figure>
        <figure>
          <%= f.label :fps %>
          <%= f.text_field :fps %>
        </figure>
        <figure>
          <%= f.label :bluetooth %>
          <%= f.text_field :bluetooth %>
        </figure>
        <figure>
          <%= f.label :battery, "Емкость батареи" %>
          <%= f.text_field :battery %>
        </figure>
        <figure>
          <%= f.label :standby_time, "Время работы в режиме ожидания" %>
          <%= f.text_field :standby_time %>
        </figure>
        <figure>
          <%= f.label :talk_time, "Время работы в режиме разговора" %>
          <%= f.text_field :talk_time %>
        </figure>
        <figure>
          <%= f.label :os, "Операционная система" %>
          <%= f.text_field :os %>
        </figure>
        <figure>
          <%= f.label :color, "Цвета" %>
          <%= f.text_field :color %>
        </figure>
        <figure>
          <%= f.label :weight, "Вес" %>
          <%= f.text_field :weight %>
        </figure>
        <figure>
          <%= f.label :dimensions, "Размеры (ДxШxВ)" %>
          <%= f.text_field :dimensions %>
        </figure>
        <figure>
          <%= f.label :material, "Материал корпуса" %>
          <%= f.text_field :material %>
        </figure>
        <figure>
          <%= f.label :protection, "Степень защиты" %>
          <%= f.text_field :protection %>
        </figure>
        <figure>
          <%= f.label :hdr, "HDR" %>
          <div>
            <%= radio_button_tag(:hdr, "true") %>
            <%= label_tag(:hdr, "Есть") %>
            <%= radio_button_tag(:hdr, "false") %>
            <%= label_tag(:hdr, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :nfc, "NFC" %>
          <div>
            <%= radio_button_tag(:nfc, "true") %>
            <%= label_tag(:nfc, "Есть") %>
            <%= radio_button_tag(:nfc, "false") %>
            <%= label_tag(:nfc, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :gyroscope, "Гироскоп" %>
          <div>
            <%= radio_button_tag(:gyroscope, "true") %>
            <%= label_tag(:gyroscope, "Есть") %>
            <%= radio_button_tag(:gyroscope, "false") %>
            <%= label_tag(:gyroscope, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :accelerometer, "Акселерометр" %>
          <div>
            <%= radio_button_tag(:accelerometer, "true") %>
            <%= label_tag(:accelerometer, "Есть") %>
            <%= radio_button_tag(:accelerometer, "false") %>
            <%= label_tag(:accelerometer, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :light_sensor, "Датчик освещенности" %>
          <div>
            <%= radio_button_tag(:light_sensor, "true") %>
            <%= label_tag(:light_sensor, "Есть") %>
            <%= radio_button_tag(:light_sensor, "false") %>
            <%= label_tag(:light_sensor, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :proximity, "Датчик приближения" %>
          <div>
            <%= radio_button_tag(:proximity, "true") %>
            <%= label_tag(:proximity, "Есть") %>
            <%= radio_button_tag(:proximity, "false") %>
            <%= label_tag(:proximity, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :compass, "Цифровой компас" %>
          <div>
            <%= radio_button_tag(:compass, "true") %>
            <%= label_tag(:compass, "Есть") %>
            <%= radio_button_tag(:compass, "false") %>
            <%= label_tag(:compass, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :wireless_charge, "Беспроводная зарядка" %>
          <div>
            <%= radio_button_tag(:wireless_charge, "true") %>
            <%= label_tag(:wireless_charge, "Есть") %>
            <%= radio_button_tag(:wireless_charge, "false") %>
            <%= label_tag(:wireless_charge, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :fast_charge, "Быстрая зарядка" %>
          <div>
            <%= radio_button_tag(:fast_charge, "true") %>
            <%= label_tag(:fast_charge, "Есть") %>
            <%= radio_button_tag(:fast_charge, "false") %>
            <%= label_tag(:fast_charge, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :type_c, "USB Type-C" %>
          <div>
            <%= radio_button_tag(:type_c, "true") %>
            <%= label_tag(:type_c, "Есть") %>
            <%= radio_button_tag(:type_c, "false") %>
            <%= label_tag(:type_c, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :vr, "Виртуальная реальность" %>
          <div>
            <%= radio_button_tag(:vr, "true") %>
            <%= label_tag(:vr, "Есть") %>
            <%= radio_button_tag(:vr, "false") %>
            <%= label_tag(:vr, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :phone, "Поддержка SIM-карт" %>
          <div>
            <%= radio_button_tag(:phone, "true") %>
            <%= label_tag(:phone, "Есть") %>
            <%= radio_button_tag(:phone, "false") %>
            <%= label_tag(:phone, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :sim, "Формат SIM-карт" %>
          <%= f.text_field :sim %>
        </figure>
        <figure>
          <%= f.label :card, "Поддержка карт памяти" %>
          <div>
            <%= radio_button_tag(:card, "true") %>
            <%= label_tag(:card, "Есть") %>
            <%= radio_button_tag(:card, "false") %>
            <%= label_tag(:card, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :card_max, "Макс. объем карт памяти" %>
          <%= f.text_field :card_max %>
        </figure>
        <figure>
          <%= f.label :glonass, "Поддержка ГЛОНАСС" %>
          <div>
            <%= radio_button_tag(:glonass, "true") %>
            <%= label_tag(:glonass, "Есть") %>
            <%= radio_button_tag(:glonass, "false") %>
            <%= label_tag(:glonass, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :jack, "Разъем 3.5 мм Jack" %>
          <div>
            <%= radio_button_tag(:jack, "true") %>
            <%= label_tag(:jack, "Есть") %>
            <%= radio_button_tag(:jack, "false") %>
            <%= label_tag(:jack, "Нет") %>
          </div>
        </figure>
        <figure>
          <%= f.label :description, "Описание" %>
          <%= f.text_area :description %>
        </figure>
        <figure>
          <%= f.label :three_g, "3G" %>
          <%= f.text_area :three_g %>
        </figure>
        <figure>
          <%= f.label :four_g, "4G" %>
          <%= f.text_area :four_g %>
        </figure>
        <figure>
          <%= f.label :wifi %>
          <%= f.text_area :wifi %>
        </figure>
      </section>
      <%= f.submit(class: "button", value: "Сохранить") %>
      <%= link_to "Назад", tablets_path(:id), class: "button" %>
    <% end %>
  </div>
</main>

app/views/tablets/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', tablets_path %>

app/views/tablets/index.html.erb
<main>
  <div class="container">
    <div class="sorting">

    </div>
    <h2>Планшеты</h2>
    <section class="line">
      <div>
        <% @tablets.each do |tablet| %>
          <%= link_to tablet_path(tablet) do %>
            <article>
              <%= image_tag 'tablets/'+tablet.model, alt: tablet.model %>
              <p><%= tablet.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</main>

app/views/tablets/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', tablets_path %>

app/views/tablets/show.html.erb
<main>
  <div class="container">
    <%= link_to tablets_path do %><h2>Планшеты<% end %> > <%= @tablet.model %></h2>
    <section class="gadget-head">
      <div class="img-box">
        <%= link_to (image_path 'tablets/'+@tablet.model+'_full'), 'data-fancybox' => 'gallery' do %>
          <% image_tag 'tablets/'+@tablet.model %>
        <% end %>
        <%= link_to (image_path 'tablets/'+@tablet.model+'_full_back'), 'data-fancybox' => 'gallery' do %>
        <% end %>
      </div>
      <div class="main-specs">
        <h1 class="gadget-caption">Смартфон <%= @developer.name %> <%= @tablet.model %></h1>
        <table class="specs">
          <caption>Основные характеристики:</caption>
          <tr>
            <td>Производитель:</td>
            <td><%= @developer.name %></td>
          </tr>
          <tr>
            <td>Модель:</td>
            <td><%= @tablet.model %></td>
          </tr>
          <tr>
            <td>Год выпуска:</td>
            <td><%= @tablet.m_year %></td>
          </tr>
          <tr>
            <td>Операционная система:</td>
            <td><%= @tablet.os %></td>
          </tr>
        </table>
      </div>
      <div class="edit-buttons">
        <!-- <%= link_to 'Сравнить', edit_tablet_path(@tablet), class: "button" %>
        <%= link_to 'Избранное', edit_tablet_path(@tablet), class: "button" %> -->
        <%= link_to 'Редактировать', edit_tablet_path(@tablet), class: "button" %>
        <%= link_to 'Удалить', tablet_path(@tablet), method: :delete, data: { confirm: 'Вы уверены?' }, class: "button attention" %>
      </div>
    </section>
    <table class="specs">
      <caption>Все характеристики:</caption>
      <tr>
        <td class="sub-heading">Описание:</td>
      </tr>
      <tr>
        <td colspan="4"><%= @phone.description %></td>
      </tr>
      <tr>
        <td class="sub-heading">Дисплей:</td>
      </tr>
      <tr>
        <td>Разрешение экрана:</td>
        <td><%= @phone.resolution_x %> x <%= @phone.resolution_y %> px</td>
        <td>Диагональ экрана (дюймы):</td>
        <td><%= @phone.diagonal %></td>
      </tr>
      <tr>
        <td>Тип экрана:</td>
        <td><%= @phone.screen_type %></td>
        <td>DPI (точек на дюйм):</td>
        <td><%= @phone.dpi %> ppi</td>
      </tr>
      <tr>
        <td>Мультитач (одновременных касаний):</td>
        <td><%= @phone.multitouch %></td>
        <td>Защитное стекло:</td>
        <td><%= @phone.disp_protect %></td>
      </tr>
      <tr>
        <td class="sub-heading">Процессор:</td>
      </tr>
      <tr>
        <td>CPU:</td>
        <td><%= @phone.cpu %></td>
        <td>Количество ядер:</td>
        <td><%= @phone.cores %></td>
      </tr>
      <tr>
        <td>Частота ядер процессора:</td>
        <td><%= @phone.frequency %> GHz</td>
        <td>GPU:</td>
        <td><%= @phone.gpu %></td>
      </tr>
      <tr>
        <td class="sub-heading">Память:</td>
      </tr>
      <tr>
        <td>Внутренняя память:</td>
        <td><%= @phone.inner_mem %> GB</td>
        <td>Оперативная память:</td>
        <td><%= @phone.ram %> GB</td>
      </tr>
      <tr>
        <td>Поддержка карт памяти:</td>
        <td><%= @phone.card %></td>
        <td>Максимальный объем карт памяти (GB):</td>
        <td><%= @phone.card_max %></td>
      </tr>
      <tr>
        <td class="sub-heading">Камера:</td>
      </tr>
      <tr>
        <td>Модуль камеры:</td>
        <td><%= @phone.cam %></td>
        <td>Количество мегапикселей:</td>
        <td><%= @phone.megapixels %> MP</td>
      </tr>
      <tr>
        <td>Разрешение фотографий:</td>
        <td><%= @phone.photo_res_x %> x <%= @phone.photo_res_y %> px</td>
        <td>Разрешение видео:</td>
        <td><%= @phone.video_res_x %> x <%= @phone.video_res_y %> px</td>
      </tr>
      <tr>
        <td>FPS (Кадров в секунду):</td>
        <td><%= @phone.fps %></td>
        <td>HDR:</td>
        <td><%= @phone.hdr %></td>
      </tr>
      <tr>
        <td>Автофокус:</td>
        <td><%= @phone.autofocus %></td>
        <td>Диафрагма:</td>
        <td><%= @phone.diaphragm %></td>
      </tr>
      <tr>
        <td>Количество мегапикселей фронт. камеры:</td>
        <td><%= @phone.front_megapixels %> MP</td>
      </tr>
      <tr>
        <td class="sub-heading">Беспроводные интерфейсы:</td>
      </tr>
      <tr>
        <td>3G:</td>
      </tr>
      <tr>
        <td colspan="4" style="color: #009688"><%= @phone.three_g %></td>
      </tr>
      <tr>
        <td>4G:</td>
      </tr>
      <tr>
        <td colspan="4" style="color: #009688"><%= @phone.four_g %></td>
      </tr>
      <tr>
        <td>WiFi:</td>
        <td><%= @phone.wifi %></td>
        <td>Bluetooth:</td>
        <td><%= @phone.bluetooth %></td>
      </tr>
      <tr>
        <td>NFC:</td>
        <td><%= @phone.nfc %></td>
        <td>Беспроводная зарядка:</td>
        <td><%= @phone.wireless_charge %></td>
      </tr>
      <tr>
        <td>GLONASS:</td>
        <td><%= @phone.glonass %></td>
      </tr>
      <tr>
        <td class="sub-heading">Датчики:</td>
      </tr>
      <tr>
        <td>Гироскоп:</td>
        <td><%= @phone.gyroscope %></td>
        <td>Акселерометр:</td>
        <td><%= @phone.accelerometer %></td>
      </tr>
      <tr>
        <td>Датчик освещенности:</td>
        <td><%= @phone.light_sensor %></td>
        <td>Датчик приближения:</td>
        <td><%= @phone.proximity %></td>
      </tr>
      <tr>
        <td class="sub-heading">Время работы:</td>
      </tr>
      <tr>
        <td>Время работы в режиме ожидания:</td>
        <td><%= @phone.standby_time %> ч.</td>
        <td>Время работы в режиме разговора:</td>
        <td><%= @phone.talk_time %> ч.</td>
      </tr>
        <td>Батарея:</td>
        <td><%= @phone.battery %> mAh</td>
      <tr>
        <td class="sub-heading">Прочее:</td>
      </tr>
      <tr>
        <td>Быстрая зарядка:</td>
        <td><%= @phone.fast_charge %></td>
        <td>Разъем USB 3.0 Type-C:</td>
        <td><%= @phone.type_c %></td>
      </tr>
      <tr>
        <td>Поддержка SIM-карт:</td>
        <td><%= @phone.phone %></td>
        <td>Цвета:</td>
        <td><%= @phone.color %></td>
      </tr>
      <tr>
        <td>Вес:</td>
        <td><%= @phone.weight %> гр.</td>
        <td>Размеры (ДxШxВ):</td>
        <td><%= @phone.dimensions %></td>
      </tr>
      <tr>
        <td>Материал корпуса:</td>
        <td><%= @phone.material %></td>
        <td>Степень защиты:</td>
        <td><%= @phone.protection %></td>
      </tr>
      <tr>
        <td>Размер SIM:</td>
        <td><%= @phone.sim %></td>
        <td>Разъем 3.5 мм Jack:</td>
        <td><%= @phone.jack %></td>
      </tr>
    </table>
  </div>
  <%= render 'layouts/footer' %>
</main>