config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  resources :phones, controller: 'phones'
  resources :tablets, controller: 'tablets'
  resources :transformers, controller: 'transformers'
  resources :watches, controller: 'watches'

  root 'main#index'

  resources :phones do
    resources :developers, controller: 'developers'
  end

  root 'phones#index'

  resources :tablets do
    resources :developers, controller: 'developers'
  end

  root 'tablets#index'

  resources :watches do
    resources :developers, controller: 'developers'
  end

  root 'watches#index'

  resources :transformers do
    resources :developers, controller: 'developers'
  end

  root 'transformers#index'

  resources :developers do
    resources :phones, controller: 'phones'
    resources :tablets, controller: 'tablets'
    resources :transformers, controller: 'transformers'
    resources :watches, controller: 'watches'
  end

  root 'developers#index'
end

app/models/watch.rb
class Watch < ApplicationRecord
  has_one :developer
  validates :model, presence: true,
                        length: { minimum: 3 }
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController

  http_basic_authenticate_with name: 'Twirx', password: 'maslenak', except: [:index, :show]

  def index
    @watches = Watch.all
  end

  def show
    @watch = Watch.find(params[:id])
    @developer = Developer.find(params[:id])
  end

  def new
    @watch = Watch.new
    @developers = Developer.all
  end

  def edit
    @watch = Watch.find(params[:id])
    @developers = Developer.all
  end

  def create
    @watch = Watch.new(watch_params)
    @developers = Developer.all

    if @watch.save
      redirect_to @watch
    else
      render 'new'
    end
  end

  def update
    @watch = Watch.find(params[:id])
    @developers = Developer.all

    if @watch.update(watch_params)
      redirect_to @watch
    else
      render 'edit'
    end
  end

  def destroy
    @watch = Watch.find(params[:id])
    @watch.destroy

    redirect_to watches_path
  end

  private
    def watch_params
      params.require(:watch).permit(:model, :description, :resolution_x, :resolution_y, :diagonal, :screen_type, :color_screen, :dpi, :touchscreen, :multitouch, :cpu, :cores, :frequency, :gpu, :inner_mem, :ram, :finder, :phone, :e_mail, :wifi, :bluetooth, :nfc, :gps, :gyroscope, :accelerometer, :barometer, :thermometer, :compass, :chronograph, :pedometer, :pulse_sensor, :fitness_tracker, :wireless_charge, :fast_charge, :type_c, :battery, :standby_time, :clock_time, :os, :online_service, :compatibility, :speaker, :mic,  :color, :weight, :dimensions, :material, :protection, :m_year, :disp_protect, :glonass, :light_sensor)
    end
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/watches/_form.html.erb
<main>
  <div class="container">
    <h2>Планшет <%= @developer.name %> <%= @watch.model %></h2>
    <%= form_for @watch do |f| %>
      <% if @watch.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@watch.errors.count, "error") %> prohibited
            this watch from being saved:
          </h2>
          <ul>
            <% @watch.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <section class="device-form">
        <figure>
          <p>Разработчик</p>
          <select>
            <% @developers.each do |developer| %>
              <option><%= developer.name %></option>
              <% end %>
            </select>
          </figure>
          <figure>
            <%= f.label :description, "Описание" %>
            <%= f.text_area :description %>
          </figure>
          <figure>
            <%= f.label :model, "Модель" %>
            <%= f.text_field :model %>
          </figure>
          <figure>
            <%= f.label :m_year, "Год выхода" %>
            <%= f.text_field :m_year %>
          </figure>
          <figure>
            <%= f.label :resolution_x, "Разрешение экрана (x)" %>
            <%= f.text_field :resolution_x %>
          </figure>
          <figure>
            <%= f.label :resolution_y, "Разрешение экрана (y)" %>
            <%= f.text_field :resolution_y %>
          </figure>
          <figure>
            <%= f.label :diagonal, "Диагональ экрана" %>
            <%= f.text_field :diagonal %>
          </figure>
          <figure>
            <%= f.label :screen_type, "Тип экрана" %>
            <%= f.text_field :screen_type %>
          </figure>
          <figure>
            <%= f.label :dpi, "DPI" %>
            <%= f.text_field :dpi %>
          </figure>
          <figure>
            <%= f.label :multitouch, "Кол-во одновременных касаний" %>
            <%= f.text_field :multitouch %>
          </figure>
          <figure>
            <%= f.label :cpu, "Процессор" %>
            <%= f.text_field :cpu %>
          </figure>
          <figure>
            <%= f.label :cores, "Кол-во ядер" %>
            <%= f.text_field :cores %>
          </figure>
          <figure>
            <%= f.label :frequency, "Частота процессора" %>
            <%= f.text_field :frequency %>
          </figure>
          <figure>
            <%= f.label :gpu, "Графический процессор"%>
            <%= f.text_field :gpu %>
          </figure>
          <figure>
            <%= f.label :inner_mem, "Объем внутр. памяти" %>
            <%= f.text_field :inner_mem %>
          </figure>
          <figure>
            <%= f.label :ram, "Объем опер. памяти" %>
            <%= f.text_field :ram %>
          </figure>
          <figure>
            <%= f.label :wifi, "WiFi" %>
            <%= f.text_area :wifi %>
          </figure>
          <figure>
            <%= f.label :bluetooth, "Bluetooth" %>
            <%= f.text_field :bluetooth %>
          </figure>
          <figure>
            <%= f.label :battery, "Емкость батареи" %>
            <%= f.text_field :battery %>
          </figure>
          <figure>
            <%= f.label :standby_time, "Время работы в режиме ожидания" %>
            <%= f.text_field :standby_time %>
          </figure>
          <figure>
            <%= f.label :clock_time, "Время работы в режиме часов" %>
            <%= f.text_field :clock_time %>
          </figure>
          <figure>
            <%= f.label :os, "Операционная система" %>
            <%= f.text_field :os %>
          </figure>
          <figure>
            <%= f.label :color, "Цвета" %>
            <%= f.text_field :color %>
          </figure>
          <figure>
            <%= f.label :weight, "Вес" %>
            <%= f.text_field :weight %>
          </figure>
          <figure>
            <%= f.label :dimensions, "Размеры (ДxШxВ)" %>
            <%= f.text_field :dimensions %>
          </figure>
          <figure>
            <%= f.label :material, "Материал корпуса" %>
            <%= f.text_field :material %>
          </figure>
          <figure>
            <%= f.label :protection, "Степень защиты" %>
            <%= f.text_field :protection %>
          </figure>
          <figure>
            <%= f.label :online_service, "Онлайн-сервис" %>
            <%= f.text_field :online_service %>
          </figure>
          <figure>
            <%= f.label :compatibility, "Совместимость" %>
            <%= f.text_field :compatibility %>
          </figure>
          <figure>
            <%= f.label :gps, "GPS" %>
            <div>
              <%= radio_button_tag(:gps, "true") %>
              <%= label_tag(:gps, "Есть") %>
              <%= radio_button_tag(:gps, "false") %>
              <%= label_tag(:gps, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :nfc, "NFC" %>
            <div>
              <%= radio_button_tag(:nfc, "true") %>
              <%= label_tag(:nfc, "Есть") %>
              <%= radio_button_tag(:nfc, "false") %>
              <%= label_tag(:nfc, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :gyroscope, "Гироскоп" %>
            <div>
              <%= radio_button_tag(:gyroscope, "true") %>
              <%= label_tag(:gyroscope, "Есть") %>
              <%= radio_button_tag(:gyroscope, "false") %>
              <%= label_tag(:gyroscope, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :accelerometer, "Акселерометр" %>
            <div>
              <%= radio_button_tag(:accelerometer, "true") %>
              <%= label_tag(:accelerometer, "Есть") %>
              <%= radio_button_tag(:accelerometer, "false") %>
              <%= label_tag(:accelerometer, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :barometer, "Барометр" %>
            <div>
              <%= radio_button_tag(:barometer, "true") %>
              <%= label_tag(:barometer, "Есть") %>
              <%= radio_button_tag(:barometer, "false") %>
              <%= label_tag(:barometer, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :thermometer, "Термометр" %>
            <div>
              <%= radio_button_tag(:thermometer, "true") %>
              <%= label_tag(:thermometer, "Есть") %>
              <%= radio_button_tag(:thermometer, "false") %>
              <%= label_tag(:thermometer, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :compass, "Компас" %>
            <div>
              <%= radio_button_tag(:compass, "true") %>
              <%= label_tag(:compass, "Есть") %>
              <%= radio_button_tag(:compass, "false") %>
              <%= label_tag(:compass, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :chronograph, "Хронограф" %>
            <div>
              <%= radio_button_tag(:chronograph, "true") %>
              <%= label_tag(:chronograph, "Есть") %>
              <%= radio_button_tag(:chronograph, "false") %>
              <%= label_tag(:chronograph, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :pedometer, "Шагомер" %>
            <div>
              <%= radio_button_tag(:pedometer, "true") %>
              <%= label_tag(:pedometer, "Есть") %>
              <%= radio_button_tag(:pedometer, "false") %>
              <%= label_tag(:pedometer, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :pulse_sensor, "Датчик пульса" %>
            <div>
              <%= radio_button_tag(:pulse_sensor, "true") %>
              <%= label_tag(:pulse_sensor, "Есть") %>
              <%= radio_button_tag(:pulse_sensor, "false") %>
              <%= label_tag(:pulse_sensor, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :wireless_charge, "Беспроводная зарядка" %>
            <div>
              <%= radio_button_tag(:wireless_charge, "true") %>
              <%= label_tag(:wireless_charge, "Есть") %>
              <%= radio_button_tag(:wireless_charge, "false") %>
              <%= label_tag(:wireless_charge, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :fast_charge, "Быстрая зарядка" %>
            <div>
              <%= radio_button_tag(:fast_charge, "true") %>
              <%= label_tag(:fast_charge, "Есть") %>
              <%= radio_button_tag(:fast_charge, "false") %>
              <%= label_tag(:fast_charge, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :type_c, "USB Type-C" %>
            <div>
              <%= radio_button_tag(:type_c, "true") %>
              <%= label_tag(:type_c, "Есть") %>
              <%= radio_button_tag(:type_c, "false") %>
              <%= label_tag(:type_c, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :color_screen, "Цветной экран" %>
            <div>
              <%= radio_button_tag(:color_screen, "true") %>
              <%= label_tag(:color_screen, "Есть") %>
              <%= radio_button_tag(:color_screen, "false") %>
              <%= label_tag(:color_screen, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :touchscreen, "Сенсорный экран" %>
            <div>
              <%= radio_button_tag(:touchscreen, "true") %>
              <%= label_tag(:touchscreen, "Есть") %>
              <%= radio_button_tag(:touchscreen, "false") %>
              <%= label_tag(:touchscreen, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :finder, "Поиск устройства" %>
            <div>
              <%= radio_button_tag(:finder, "true") %>
              <%= label_tag(:finder, "Есть") %>
              <%= radio_button_tag(:finder, "false") %>
              <%= label_tag(:finder, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :phone, "Поддержка звонков" %>
            <div>
              <%= radio_button_tag(:phone, "true") %>
              <%= label_tag(:phone, "Есть") %>
              <%= radio_button_tag(:phone, "false") %>
              <%= label_tag(:phone, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :e_mail, "Поддержка электронной почты" %>
            <div>
              <%= radio_button_tag(:e_mail, "true") %>
              <%= label_tag(:e_mail, "Есть") %>
              <%= radio_button_tag(:e_mail, "false") %>
              <%= label_tag(:e_mail, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :fitness_tracker, "Фитнес-трекер" %>
            <div>
              <%= radio_button_tag(:fitness_tracker, "true") %>
              <%= label_tag(:fitness_tracker, "Есть") %>
              <%= radio_button_tag(:fitness_tracker, "false") %>
              <%= label_tag(:fitness_tracker, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :speaker, "Динамик" %>
            <div>
              <%= radio_button_tag(:speaker, "true") %>
              <%= label_tag(:speaker, "Есть") %>
              <%= radio_button_tag(:speaker, "false") %>
              <%= label_tag(:speaker, "Нет") %>
            </div>
          </figure>
          <figure>
            <%= f.label :mic, "Микрофон" %>
            <div>
              <%= radio_button_tag(:mic, "true") %>
              <%= label_tag(:mic, "Есть") %>
              <%= radio_button_tag(:mic, "false") %>
              <%= label_tag(:mic, "Нет") %>
            </div>
          </figure>
        </section>
        <%= f.submit(class: "button", value: "Сохранить") %>
        <%= link_to "Назад", transformers_path(:id), class: "button" %>
    <% end %>
  </div>
</main>

app/views/watches/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', watches_path %>

app/views/watches/index.html.erb
<main class="main">
  <div class="container">
    <div class="sorting">

    </div>
    <h2>Умные часы</h2>
    <section class="line">
      <div>
        <% @watches.each do |watch| %>
          <%= link_to watch_path(watch) do %>
            <article>
              <%= image_tag 'watches/'+watch.model, alt: watch.model %>
              <p><%= watch.model %></p>
            </article>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
  <%= render 'layouts/footer' %>
</main>

app/views/watches/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', watches_path %>

app/views/watches/show.html.erb
<main class="main">
  <div class="container">
    <%= link_to watches_path do %><h2>Телефоны<% end %> > <%= @watch.model %></h2>
    <section class="gadget-head">
      <h1 class="gadget-caption">Часы <%= @watch.model %></h1>
      <div class="img-box">
        <%= link_to (image_path 'watches/'+@watch.model+'_full'), 'data-fancybox' => 'gallery' do %>
          <% image_tag 'watches/'+@watch.model %>
        <% end %>
        <%= link_to (image_path 'watches/'+@watch.model+'_full_back'), 'data-fancybox' => 'gallery' do %>
        <% end %>
      </div>
      <div class="main-specs">
        <table class="specs">
          <caption>Основные характеристики:</caption>
          <tr>
            <td>Производитель:</td>
            <td>LG</td>
          </tr>
          <tr>
            <td>Модель:</td>
            <td><%= @watch.model %></td>
          </tr>
          <tr>
            <td>Год выпуска:</td>
            <td><%= @watch.m_year %></td>
          </tr>
          <tr>
            <td>Операционная система:</td>
            <td><%= @watch.os %></td>
          </tr>
        </table>
      </div>
      <div class="edit-buttons">
        <!-- <%= link_to 'Сравнить', edit_watch_path(@watch), class: "button" %>
        <%= link_to 'Избранное', edit_watch_path(@watch), class: "button" %> -->
        <%= link_to 'Редактировать', edit_watch_path(@watch), class: "button" %>
        <%= link_to 'Удалить', watch_path(@watch), method: :delete, data: { confirm: 'Вы уверены?' }, class: "button attention" %>
      </div>
    </section>
    <table class="specs">
      <caption>Все характеристики:</caption>
      <tr>
        <td class="sub-heading">Описание:</td>
      </tr>
      <tr>
        <td colspan="4"><%= @transformer.description %></td>
      </tr>
      <tr>
        <td class="sub-heading">Дисплей:</td>
      </tr>
      <tr>
        <td>Разрешение экрана:</td>
        <td><%= @transformer.resolution_x %> x <%= @transformer.resolution_y %> px</td>
        <td>Диагональ экрана (дюймы):</td>
        <td><%= @transformer.diagonal %></td>
      </tr>
      <tr>
        <td>Тип экрана:</td>
        <td><%= @transformer.screen_type %></td>
        <td>DPI (точек на дюйм):</td>
        <td><%= @transformer.dpi %> ppi</td>
      </tr>
      <tr>
        <td>Мультитач (одновременных касаний):</td>
        <td><%= @transformer.multitouch %></td>
        <td>Защитное стекло:</td>
        <td><%= @transformer.disp_protect %></td>
      </tr>
      <tr>
        <td class="sub-heading">Процессор:</td>
      </tr>
      <tr>
        <td>CPU:</td>
        <td><%= @transformer.cpu %></td>
        <td>Количество ядер:</td>
        <td><%= @transformer.cores %></td>
      </tr>
      <tr>
        <td>Частота ядер процессора:</td>
        <td><%= @transformer.frequency %> GHz</td>
        <td>GPU:</td>
        <td><%= @transformer.gpu %></td>
      </tr>
      <tr>
        <td class="sub-heading">Память:</td>
      </tr>
      <tr>
        <td>Внутренняя память:</td>
        <td><%= @transformer.inner_mem %> GB</td>
        <td>Оперативная память:</td>
        <td><%= @transformer.ram %> GB</td>
      </tr>
      <tr>
        <td class="sub-heading">Беспроводные интерфейсы:</td>
      </tr>
      <tr>
        <td>WiFi:</td>
        <td><%= @transformer.wifi %></td>
        <td>Bluetooth:</td>
        <td><%= @transformer.bluetooth %></td>
      </tr>
      <tr>
        <td>GLONASS:</td>
        <td><%= @transformer.glonass %></td>
      </tr>
      <tr>
        <td class="sub-heading">Датчики:</td>
      </tr>
      <tr>
        <td>Гироскоп:</td>
        <td><%= @transformer.gyroscope %></td>
        <td>Акселерометр:</td>
        <td><%= @transformer.accelerometer %></td>
      </tr>
      <tr>
        <td>Барометр:</td>
        <td><%= @transformer.barometer %></td>
        <td>Термометр:</td>
        <td><%= @transformer.thermometer %></td>
      </tr>
      <tr>
        <td>Компас:</td>
        <td><%= @transformer.compass %></td>
        <td>Хронограф:</td>
        <td><%= @transformer.chronograph %></td>
      </tr>
      <tr>
        <td>Шагомер:</td>
        <td><%= @transformer.pedometer %></td>
        <td>Датчик пульса:</td>
        <td><%= @transformer.pulse_sensor %></td>
      </tr>
      <tr>
        <td>Датчик освещенности:</td>
        <td><%= @transformer.light_sensor %></td>
      </tr>
      <tr>
        <td class="sub-heading">Время работы:</td>
      </tr>
      <tr>
        <td>Время работы в режиме ожидания:</td>
        <td><%= @transformer.standby_time %> ч.</td>
        <td>Время работы в режиме часов:</td>
        <td><%= @transformer.clock_time %> ч.</td>
      </tr>
      <tr>
        <td>Батарея:</td>
        <td><%= @transformer.battery %> mAh</td>
      </tr>
      <tr>
        <td class="sub-heading">Прочее:</td>
      </tr>
      <tr>
        <td>Быстрая зарядка:</td>
        <td><%= @transformer.fast_charge %></td>
        <td>Фитнес-трекер:</td>
        <td><%= @transformer.fitness_tracker %></td>
      </tr>
      <tr>
        <td>Беспроводная зарядка:</td>
        <td><%= @transformer.wireless_charge %></td>
        <td>Цвета:</td>
        <td><%= @transformer.color %></td>
      </tr>
      <tr>
        <td>Вес:</td>
        <td><%= @transformer.weight %> гр.</td>
        <td>Размеры (ДxШxВ):</td>
        <td><%= @transformer.dimensions %></td>
      </tr>
      <tr>
        <td>Материал корпуса:</td>
        <td><%= @transformer.material %></td>
        <td>Степень защиты:</td>
        <td><%= @transformer.protection %></td>
      </tr>
      <tr>
        <td>Разъем 3.5 мм Jack:</td>
        <td><%= @transformer.jack %></td>
        <td>Разъем USB Type-C:</td>
        <td><%= @transformer.type_c %></td>
      </tr>
      <tr>
        <td>Онлайн-сервис:</td>
        <td><%= @transformer.online_service %></td>
        <td>Совместимость:</td>
        <td><%= @transformer.compatibility %></td>
      </tr>
      <tr>
        <td>Микрофон:</td>
        <td><%= @transformer.mic %></td>
        <td>Динамик:</td>
        <td><%= @transformer.speaker %></td>
      </tr>
    </table>
  </div>
  <%= render 'layouts/footer' %>
</main>